- .github/workflows/bug-issue-notify.yml
✅ **7/7 완료** (모든 항목 완료!)
Closes #5
---
---
> chore:템플릿 업데이트 #5

- be15_DevEagles_BE/src/main/resources/logback-spring.xml
Backend
- 백엔드 로그 설정 추가
- 로그 레벨 설정
Closes #24
---
> [chore] logback profile 없을 시 fallback 설정

- be15_DevEagles_FE/src/components/common/TheSidebar.vue
Frontend
- 공통 컴포넌트 생성
1. 헤더
2. 레이아웃
3. 사이드바
Closes #30
---
> [common] 공통 컴포넌트 수정 - 툴팁 문구 수정 #30

- be15_DevEagles_FE/src/features/messages/components/MessageFilter.vue
- be15_DevEagles_FE/src/features/messages/components/MessageItem.vue
- be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
문자 목록 페이지 구현
Closes #35
---
> feat: 문자 목록 페이지 구현 #35

- be15_DevEagles_FE/src/features/messages/components/TemplateFilter.vue
- be15_DevEagles_FE/src/features/messages/components/TemplateItem.vue
- be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
등록된 템플릿들을 조회,수정,삭제,등록할 수 있는 관리 화면
Closes #38
---
> feat: 문자 템플릿 목록 페이지 구현 #38

- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/assets/css/components.css
- be15_DevEagles_FE/src/assets/css/styleguide.css
- be15_DevEagles_FE/src/components/common/BaseButton.vue
- be15_DevEagles_FE/src/components/common/BaseConfirm.vue
- be15_DevEagles_FE/src/components/common/BasePopover.vue
- be15_DevEagles_FE/src/components/common/index.js
- be15_DevEagles_FE/src/components/layout/index.js
- be15_DevEagles_FE/src/features/coupons/CouponForm.vue
- be15_DevEagles_FE/src/features/coupons/CouponList.vue
- be15_DevEagles_FE/src/features/coupons/index.js
- be15_DevEagles_FE/src/features/coupons/routes.js
- be15_DevEagles_FE/src/routes/index.js
Frontend
쿠폰 컴포넌트 구현
- 목록 페이지
- 쿠폰 생성, 삭제 확인 모달 구현
- Toastification 설정
Closes #41
---
> [coupons] 쿠폰 목록 - 쿠폰 목록 페이지 및 컴포넌트 구현 #41

- be15_DevEagles_FE/src/features/messages/components/modal/AlimtalkConfirmModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/PointChargeModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/SenderInfoModal.vue
- be15_DevEagles_FE/src/features/messages/views/SettingsView.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
메시지 설정 UI/UX 구현
Closes #40
---
> feat/messages/메시지 설정 UI/ux/구현#40

- be15_DevEagles_FE/src/components/layout/TheSidebar.vue
- be15_DevEagles_FE/src/features/analytics/components/charts/BaseChart.vue
- be15_DevEagles_FE/src/features/analytics/composables/useUsageAnalytics.js
- be15_DevEagles_FE/src/features/analytics/config/usageChartOptions.js
- be15_DevEagles_FE/src/features/analytics/styles/usage.css
- be15_DevEagles_FE/src/features/analytics/utils/mockUsageDataGenerator.js
- be15_DevEagles_FE/src/features/analytics/views/UsageAnalytics.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
데이터 분석 도메인
- 이용율 통계 페이지
Closes #55
---
> [analytics] 통계 컴포넌트 - 예약률 통계 페이지 구현 #55

- .gitignore
- be15_DevEagles_DA/env.example
- be15_DevEagles_DA/pyproject.toml
- be15_DevEagles_DA/src/analytics/api/main.py
- be15_DevEagles_DA/src/analytics/api/routes/__init__.py
- be15_DevEagles_DA/src/analytics/api/routes/health.py
- be15_DevEagles_DA/src/analytics/cli.py
- be15_DevEagles_DA/src/analytics/core/config.py
- be15_DevEagles_DA/src/analytics/core/database.py
- be15_DevEagles_DA/src/analytics/core/logging.py
Backend
Python DB 설정
- Sqlite : 스케쥴러용
- mariaDB : 백엔드 DB
- DuckDB : 분석용 DB
Closes #90
---
> [analytics] 개발 설정 파이썬 DB 설정#90

- be15_DevEagles_FE/src/features/messages/components/MessageStats.vue
- be15_DevEagles_FE/src/features/messages/components/TemplateSelectDrawer.vue
- be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
- be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
- be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Backend
메시지 템플릿 조회 모달 구현
Closes #96
---
> feat: 메시지 템플릿 조회 모달 구현 #96

- be15_DevEagles_DA/create_preference_samples.py
- be15_DevEagles_DA/simple_test.py
- be15_DevEagles_DA/src/analytics/cli.py
- be15_DevEagles_DA/src/analytics/models/base.py
- be15_DevEagles_DA/src/analytics/services/__init__.py
- be15_DevEagles_DA/src/analytics/services/preference.py
- be15_DevEagles_DA/src/analytics/services/segmentation.py
- be15_DevEagles_DA/test_preference.py
- be15_DevEagles_DA/test_segmentation.py
- be15_DevEagles_DA/verify_segmentation.py
Backend
파이썬 서버
- 고객 세그멘테이션 로직 구현
- Spark, Airflow 연동
Closes #99
---
> [analytics] 파이썬 서버 - 고객 세그멘테이션, 선호도 로직#99

- be15_DevEagles_FE/package.json
- be15_DevEagles_FE/src/features/staffs/components/StaffForm.vue
- be15_DevEagles_FE/src/features/staffs/components/StaffPermission.vue
- be15_DevEagles_FE/src/features/staffs/route.js
- be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
- be15_DevEagles_FE/src/features/users/components/ProfileUpload.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
- 직원 상세 페이지 링크 연결
- 직원 상세 페이지 구현
- 직원 정보 설정 컴포넌트
- 직원 접근 권한 컴포넌트 
Closes #102
---
- 직원 상세 라우팅
- 직원 정보 컴포넌트
- 직원 권한 컴포넌트
- 프로필 default 이미지 수정
- color picker 라이브러리 추가
> [staffs] 직원 컴포넌트 구현 - 직원 상세 #102

- be15_DevEagles_DA/create_risk_samples.py
- be15_DevEagles_DA/src/analytics/cli.py
- be15_DevEagles_DA/src/analytics/models/crm.py
- be15_DevEagles_DA/src/analytics/services/__init__.py
- be15_DevEagles_DA/src/analytics/services/risk_tagging.py
- be15_DevEagles_DA/test_risk_tagging.py
Backend
[analytics] 파이썬 서버 - 이탈 위험 태깅 시스템 구현
- 이탈 위험 태깅 시스템 구현
Closes #100
---
> [analytics] 이탈 위험 태깅 구현#100

- be15_DevEagles_FE/src/features/messages/components/TemplateItem.vue
- be15_DevEagles_FE/src/features/messages/components/modal/TemplateCreateModal.vue
- be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Frontend
템플릿 등록 모달 구현 및 템플릿 목록 수정
⚠️ **3/4 완료** (미완료 항목 있음)
Closes #107
---
> [messages] 템플릿 등록 모달 구현하기#107

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/BusinessException.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCodeType.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
> [common] 비즈니스 예외 코드 등록

- be15_DevEagles_FE/src/features/messages/components/modal/TemplateDeleteModal.vue
- be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Frontend
템플릿 메시지 삭제 모달 구현
⚠️ **3/4 완료** (미완료 항목 있음)
Closes #123
---
> [messages] 템플릿 삭제 모달 구현 #123

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/controller/CouponController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/controller/CouponValidationController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/query/service/CouponQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/repository/CouponQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponApplicationService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponValidationService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/query/service/CouponQueryServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponApplicationServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponDiscountCalculatorTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponValidationServiceTest.java
Backend
쿠폰 기능 구현 
- 쿠폰 생성 서비스, 컨트롤러
- 쿠폰 조회 서비스, 컨트롤러
- 쿠폰 삭제 서비스, 컨트롤러
- 쿠폰 유효성 검증 서비스, 컨트롤러
- 쿠폰 할인 계산 서비스, 컨트롤러
Closes #117
---
> [coupon] 쿠폰 기능 - 쿠폰 서비스 컨트롤러 구현#117

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/entity/Coupon.java
Backend
쿠폰 기능 구현 
- 쿠폰 생성 서비스, 컨트롤러
- 쿠폰 조회 서비스, 컨트롤러
- 쿠폰 삭제 서비스, 컨트롤러
- 쿠폰 유효성 검증 서비스, 컨트롤러
- 쿠폰 할인 계산 서비스, 컨트롤러
Closes #117
---
> [coupon] 쿠폰 엔티티 Access 레벨 누락 수정

- be15_DevEagles_FE/src/components/common/BaseTable.vue
- be15_DevEagles_FE/src/components/layout/TheSidebar.vue
- be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
- be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
- be15_DevEagles_FE/src/features/schedules/views/ScheduleLeaveView.vue
- be15_DevEagles_FE/src/features/schedules/views/SchedulePlanView.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
직원 일정 휴무 목록 조회
Closes #77
---
> [schedules] 직원 일정 휴무 목록 조회 #77

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Customer.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/CustomerGrade.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Tag.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/TagByCustomer.java
Backend
고객 도메인 엔티티 구현
- 고객
- 태그
- 고객 태그
- 고객 등급
Closes #156
---
> [customer] 고객 도메인 - 고객, 태그, 고객태그 고객등급 엔티티 구현 #156

- be15_DevEagles_FE/src/features/schedules/components/DesignerCard.vue
- be15_DevEagles_FE/src/features/schedules/routes.js
- be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
Frontend
고객 예약 페이지 구현
⚠️ **3/4 완료** (미완료 항목 있음)
Closes #164
---
> [schedules] 고객 예약 페이지 구현 #164

- be15_DevEagles_FE/src/components/icons/ListIcon.vue
- be15_DevEagles_FE/src/components/icons/NewIcon.vue
- be15_DevEagles_FE/src/components/layout/TheLayout.vue
- be15_DevEagles_FE/src/features/chat/components/ChatInput.vue
- be15_DevEagles_FE/src/features/chat/components/ChatListView.vue
- be15_DevEagles_FE/src/features/chat/components/ChatMessages.vue
- be15_DevEagles_FE/src/features/chat/components/ChatModal.vue
Backend
채팅 목록 구현
Closes #160
---
> [chat]채팅 - 채팅 목록 구현 #160

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/controller/CustomerTagController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/controller/TagController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/CreateTagRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/UpdateTagRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/response/TagResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/CustomerTagService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/TagCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/TagByCustomer.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/TagByCustomerRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/TagRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerTagServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/TagCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/TagQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/TagQueryService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/TagCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/TagQueryServiceImplTest.java
Backend
고객 백엔드 
- 생성
- 삭제
- 조회
- 고객에 태그 부여
Closes #176
---
> [customer] 고객 백엔드 - 태그 기능 구현#176

- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/components/common/BaseModal.vue
- be15_DevEagles_FE/src/features/schedules/components/DesignerCard.vue
- be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
- be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
- be15_DevEagles_FE/src/features/schedules/views/DesignerListView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
- be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
- be15_DevEagles_FE/src/features/schedules/views/ScheduleLeaveView.vue
- be15_DevEagles_FE/src/features/schedules/views/SchedulePlanView.vue
- be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Frontend
스케줄 전체 UI UX 수정
⚠️ **12/13 완료** (미완료 항목 있음)
Closes #166
---
> [schedules] UI UX 개선 #166

- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImplTest.java
- be15_DevEagles_FE/index.html
- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/components/common/BaseButton.vue
- be15_DevEagles_FE/src/components/common/BaseForm.vue
- be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
- be15_DevEagles_FE/src/features/coupons/components/CouponForm.vue
Frontend
새 쿠폰 등록 시 시간이 00:00으로 자동 초기화 됨
1. 쿠폰 관리 페이지에서 새 쿠폰 등록 버튼 누르기
2. 만료일 설정 시 시간 설정이 가능하게 하기
Closes #168
---
+ Datepicker X 아이콘 달력 아이콘 겹치는 문제도 수정
> [coupon] 버그 수정 - 시간 초기화 버그#168

- be15_DevEagles_FE/src/features/staffsales/components/TargetSalesSettingModal.vue
- be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Frontend
- 직원 결산 (목표 매출 탭)
- 목표 매출 설정 모달
Closes #139
---
> [staffs] 직원 컴포넌트 구현 - 목표 매출 #139

- be15_DevEagles_FE/index.html
- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/assets/css/primevue-theme.css
- be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
- be15_DevEagles_FE/src/main.js
Frontend
새 쿠폰 등록 시 시간이 00:00으로 자동 초기화 됨
1. 쿠폰 관리 페이지에서 새 쿠폰 등록 버튼 누르기
2. 만료일 설정 시 시간 설정이 가능하게 하기
Closes #168
---
> [common] 코드 수정 - Datepicker 관련 불필요한 코드 삭제

- be15_DevEagles_FE/src/features/users/route.js
- be15_DevEagles_FE/src/features/users/views/EmailVerifyView.vue
Frontend
- 대표자의 이메일을 통한 본인 인증 페이지 구현
Closes #187
---
> [users] 유저 컴포넌트 구현 - 본인 인증 페이지 #187

- be15_DevEagles_FE/src/features/users/components/PasswordEditForm.vue
- be15_DevEagles_FE/src/features/users/route.js
- be15_DevEagles_FE/src/features/users/views/EmailPwdEditView.vue
- be15_DevEagles_FE/src/features/users/views/EmailVerifyPwdView.vue
Frontend
- 이메일 인증을 통한 비밀번호 변경 페이지 
Closes #188
---
> [users] 유저 컴포넌트 구현 - 본인 인증 비밀번호 변경 페이지 #188

- be15_DevEagles_FE/src/features/sales/components/ItemSalesDeleteModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemSalesRefundModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemsSelectModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesDeleteModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesEditModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesRefundModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesRegistModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSelectModal.vue
- be15_DevEagles_FE/src/features/sales/components/RefundDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
- be15_DevEagles_FE/src/features/sales/components/SalesTableForm.vue
- be15_DevEagles_FE/src/features/sales/styles/SalesDetailModal.css
- be15_DevEagles_FE/src/features/sales/styles/SalesItemsModal.css
- be15_DevEagles_FE/src/features/sales/styles/SalesMembershipModal.css
Frontend
- 회원권 매출 등록 모달 구현
- 회원권 매출 수정 모달 구현
- 회원권 매출 환불 모달 구현 
- 회원권 선택 모달 구현 
- 상품 선택 모달 구현
- 상품 매출 등록 모달 구현
- 상품 매출 수정 모달 구현
- 상품 매출 환불 모달 구현 
- 매출 상세조회 모달 구현 
Closes #133
---
- 매출 페이지 모달 구현
> [sales] 매출 컴포넌트 구현 - 매출 모달 구현 #133

- be15_DevEagles_FE/src/features/item/components/ItemForm.vue
- be15_DevEagles_FE/src/features/item/components/PrimaryDeleteModal.vue
- be15_DevEagles_FE/src/features/item/components/PrimaryEditModal.vue
- be15_DevEagles_FE/src/features/item/components/PrimaryRegistModal.vue
- be15_DevEagles_FE/src/features/item/components/SecondaryDeleteModal.vue
- be15_DevEagles_FE/src/features/item/components/SecondaryEditModal.vue
- be15_DevEagles_FE/src/features/item/components/SecondaryRegistModal.vue
Frontend
- 상품 컴포넌트 UI개선
- 상품 페이지 관련 코드
Closes #194
---
- 상품 페이지 UI 개선
> [item] 상품 페이지 수정 - UI 개선 #194

- be15_DevEagles_FE/src/components/layout/TheSidebar.vue
- 예약관리 : 예약 설정 이동
- 고객관리 : 선불고객 관리 삭제
- 마케팅 : 워크플로우, 캠페인, 쿠폰 관리 이동
- 매장 설정 : 프로필링크 이동, 고객 등급 및 태그 등록 삭제
> [common] 공통 컴포넌트 수정 - 네비게이션바 변경 #201

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessList.java
Backend
- Shop Entity 생성
- Staff Entity 생성
- Industry Entity 생성
- Access_list Entity 생성
- Access_auth Entity 생성
- SNS Entity 생성 
Closes #221
---
- authId -> accessId
> [users] 엔터티 수정 - AccessListEntity 수정 #221

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/DayOfWeekEnum.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Leave.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Plan.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/RegularLeave.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/RegularPlan.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Reservation.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationDetail.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationSetting.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationStatusName.java
Backend
예약 관련 엔터티 생성 및 cqrs 구조 세팅
Closes #228
---
> [schedules] 초기 세팅 #228

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/ActionExecutorService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/CustomerFilterService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/TriggerCheckService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowExecutionService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowScheduler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/Workflow.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/WorkflowExecution.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/CustomerFilterServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowExecutionServiceTest.java
Backend
워크플로 실행 엔진 구현
- 스케쥴러 구현
- 실행 서비스
- 대상 고객 필터링 서비스
- 액션 실행 서비스
- 트리거 체크 서비스
Closes #244
---
> [workflow] 워크플로 백엔드 기능 구현 - 워크플로우 실행 엔진#244

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
Backend
- Security 설정 없이 접근을 위한 SecuriryConfig 설정  
Closes #252
---
> [Common] SecurityConfig 설정 #252

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/controller/ShopCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/ShopCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/ValidBizNumberRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/ShopRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/ShopAndUserCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/UserCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/ValidCheckRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/Staff.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/repository/UserRepository.java
- be15_DevEagles_BE/src/main/resources/application.yml
Backend
- 회원가입 API 기능 구현
- 회원 정보 등록
- 매장 정보 등록
Closes #212
---
> [usrs] 회원 기능 구현 - 회원가입 #212

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/infrastructure/repository/WorkflowJpaDataRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/request/WorkflowSearchRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowQueryResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowStatsResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowSummaryResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/service/WorkflowQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/controller/WorkflowQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/domain/repository/WorkflowQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/repository/WorkflowQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImplTest.java
Backend
워크플로우 백엔드 
- 조회 기능 구현
Closes #259
---
> [workflow] 워크플로우 백엔드 - 조회 기능#259

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/PrepaidPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/SessionPass.java
Backend
- 회원권 Entity 생성
Closes #261
---
- 회원권 관련 Entity 생성
> [membership] 회원권 - 회원권 관련 Entity 생성 #261

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/ItemSales.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Payment.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PaymentMethod.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PrepaidPassSales.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/SessionPassSales.java
Backend
- 매출 관련 Entity 생성
Closes #264
---
- 매출 관련 Entity 생성
> [sales] 매출 - 매출 관련 Entity 생성 #264

- be15_DevEagles_FE/src/components/layout/TheSidebar.vue
- be15_DevEagles_FE/src/features/messages/components/TemplateItem.vue
- be15_DevEagles_FE/src/features/messages/components/TemplateSelectDrawer.vue
- be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/ReservationSendModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/SendConfirmModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/TemplateCreateModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/TemplateDeleteModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/TemplateDetailModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/TemplateEditModal.vue
- be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
- be15_DevEagles_FE/src/features/messages/views/SettingsView.vue
- be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Frontend
- 템플릿 목록 UI 개선
- 사이드 바 명칭 및 페이지 명칭 변경
- 템플릿 등록 관련 모달 수정
- 템플릿 목록 페이지 관련 코드 
Closes #247
---
> [messages] 템플릿 목록 UI 수정#247

- .gitignore
- be15_DevEagles_FE/package.json
Frontend
Playwright CI E2E 테스트 설정
- 기본 설정
Closes #268
---
> [common] Playwright - 기본 설정 및 깃헙 워크플로우 등록 #268

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/SecondaryItemCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/PrimaryItemRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/PrimaryItemQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/dto/response/PrimaryItemResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/PrimaryItemQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PriamryItemQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PriamryItemQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/items/api/items.js
- be15_DevEagles_FE/src/features/items/components/BaseItemModal.vue
- be15_DevEagles_FE/src/features/items/components/ItemForm.vue
- be15_DevEagles_FE/src/features/items/components/PrimaryEditModal.vue
Full Stack
- 1차 상품 조회 기능 구현
- 1차 상품 조회 API 연동
Closes #210
---
> [items] 상품 기능 구현 - 1차 상품 조회 기능 구현 #210

- be15_DevEagles_FE/src/components/common/BaseWindow.vue
- be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
- be15_DevEagles_FE/src/features/campaigns/components/CampaignForm.vue
- be15_DevEagles_FE/src/features/campaigns/views/CampaignList.vue
- be15_DevEagles_FE/src/features/coupons/components/CouponDetailModal.vue
- be15_DevEagles_FE/src/features/coupons/components/CouponForm.vue
- be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
Frontend
프론트 디자인 
- 쿠폰 모달 디자인 변경
- 쿠폰 페이지 행 선택으로 상세 조회로 수정
- 캠페인 페이지 행 선택으로 상세 조회로 수정
Closes #279
---
> [coupon] 윈도우 모달 생성 - 쿠폰 폼, 캠페인 폼 및 페이지 수정#279

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/PrimaryItemCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/PrimaryItem.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/items/api/items.js
- be15_DevEagles_FE/src/features/items/components/ItemForm.vue
- be15_DevEagles_FE/src/features/items/components/PrimaryDeleteModal.vue
Full Stack
- 1차 상품 삭제 기능 구현
- 1차 상품 삭제 API 연동
Closes #207
---
> [items] 상품 기능 구현 - 1차 상품 삭제 기능 구현 #207

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/SecondaryItemRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/SecondaryItemQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/dto/response/SecondaryItemResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/SecondaryItemQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/items/api/items.js
- be15_DevEagles_FE/src/features/items/components/ItemForm.vue
- be15_DevEagles_FE/src/features/items/components/SecondaryRegistModal.vue
Full Stack
- 2차 상품 조회 기능 구현
- 2차 상품 조회 API 연동
Closes #211
---
> [items] 상품 기능 구현 - 2차 상품 조회 기능 구현 #211

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/controller/WorkflowCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCouponService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCustomerEventService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCustomerQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockMessageQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockMessageService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockNotificationService.java
- be15_DevEagles_FE/src/components/common/BaseWindow.vue
- be15_DevEagles_FE/src/components/common/CompactTemplateSelector.vue
- be15_DevEagles_FE/src/components/common/TemplateForm.vue
- be15_DevEagles_FE/src/components/common/TemplateSelectorModal.vue
- be15_DevEagles_FE/src/components/icons/PlusIcon.vue
- be15_DevEagles_FE/src/components/icons/TicketIcon.vue
- be15_DevEagles_FE/src/components/icons/XIcon.vue
- be15_DevEagles_FE/src/components/icons/index.js
- be15_DevEagles_FE/src/features/coupons/components/CompactCouponSelector.vue
- be15_DevEagles_FE/src/features/coupons/components/CouponSelectorModal.vue
- be15_DevEagles_FE/src/features/coupons/index.js
- be15_DevEagles_FE/src/features/workflows/components/WorkflowConfigSidebar.vue
- be15_DevEagles_FE/src/features/workflows/components/WorkflowFormBase.vue
Frontend
쿠폰 프론트 기능 구현 
- 쿠폰 선택창 구현
- 생성 버튼 연결
Closes #286
---
> [coupon] 쿠폰 프론트 -  선택창 디자인, 생성 모달 연결#286

- .github/workflows/playwright.yml
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/AcquisitionChannelController.java
> [common] playwright - 실패 플로우 수정

- .github/workflows/playwright.yml
> chore: playwright 워크플로우 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/PlanQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/PlanListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/mapper/PlanQueryMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/PlanQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/schedules/PlanQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/PlanQueryServiceTest.java
Backend
정기 일정 리스트 조회 시 날짜 부분 수정
1. 일정 목록 조회 
2. 조회 되는 데이터 수정
Closes #298
---
> [schedules] 일정 기능 개선 #298

- be15_DevEagles_FE/src/components/common/BaseDrawer.vue
- be15_DevEagles_FE/src/features/customer/components/CustomerEditDrawer.vue
- be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
Frontend
- 고객 상세 정보 모달 구현
Closes #175
---
-고객수정드로어 생성 시 고객 상세 정보 모달창이 닫히는 문제 해결
> [customer] 고객상세정보모달#175

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/RedisConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/request/LoginRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/response/TokenResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenServiceImpl.java
- be15_DevEagles_BE/src/main/resources/application.yml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/application/service/AuthServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/users/api/users.js
- be15_DevEagles_FE/src/features/users/views/LoginView.vue
Full Stack
- Backend
- 로그인 API 기능 구현
- Frontend
- 로그인API 연동
Closes #214
---
> [users] 회원 기능 구현 - 로그인 기능 구현 #214

- be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
- be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
- be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Frontend
- 리팩토링 대상 : schedules 프론트 파일
- 현재 문제점: 공통 스타일 변화로 인한 ux 불편
- 개선 방향: 가독성 개성 및 스타일 개선
- 수정될 파일들 : schedules 프론트 
- 영향받는 기능들 : 예약 일정 휴무
- 호환성 고려상항 : x
⚠️ **2/4 완료** (미완료 항목 있음)
Closes #313
---
> [schedules] schedules 프론트 수정 #313

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtAuthenticationFilter.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAccessDeniedHandler.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAuthenticationEntryPoint.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/application/service/AuthServiceImplTest.java
- be15_DevEagles_FE/src/App.vue
- be15_DevEagles_FE/src/components/layout/TheHeader.vue
- be15_DevEagles_FE/src/features/users/views/AccountSettingView.vue
- be15_DevEagles_FE/src/features/users/views/LoginView.vue
- be15_DevEagles_FE/src/main.js
- be15_DevEagles_FE/src/plugins/axios.js
- be15_DevEagles_FE/src/store/auth.js
- be15_DevEagles_FE/src/store/userStatus.js
Full Stack
- BackEnd 
- SpringSecurity 적용
- Token 저장
- FrontEnd
- Pinia 연결  
Closes #316
---
> [users] 회원 기능 구현 - 인증/인가 설정 구현 #316

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/Staff.java
Backend
회원 정보 등록 시 필수 값 누락으로  데이터베이스 오류 발생
- 회원 데이터 등록 요청 시 colorCode, staff_status 값 누락된 상태로 등록 요청
> [users] 회원 기능 구현 - 회원 가입 필수 값 누락

- be15_DevEagles_BE/build.gradle
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsSendEvent.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/SmsResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/SmsSendEventListener.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageKind.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/Sms.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/SmsRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/infrastructure/CoolSmsClient.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
- be15_DevEagles_BE/src/main/resources/application.yml
Backend
문자 보내기 기능 구현
Closes #307
---
> [messages] 문자 보내기 구현#307

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/PrepaidPassSalesCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/SessionPassSalesCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PaymentsInfo.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PrepaidPassSalesRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/SessionPassSalesRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/PrepaidPassSalesCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/SessionPassSalesCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Payments.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PaymentsMethod.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PaymentsRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PrepaidPassSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SessionPassSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaPaymentsRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaPrepaidPassSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaSessionPassSalesRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Full Stack
- 회원권 매출 등록 기능 구현
- 상품 매출 등록 기능 구현 
- API 연동
- UI 수정
Closes #329
---
> [sales] 매출 기능 구현 - 회원권 매출 등록 기능 구현 #329

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/SecondaryItemCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/SecondaryItem.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/PrimaryItemRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/SecondaryItemRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/PrimaryItemQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/SecondaryItemQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/PrimaryItemQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/SecondaryItemQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/items/components/BaseItemModal.vue
- be15_DevEagles_FE/src/features/items/components/ItemForm.vue
Full Stack
- 클래스 및 함수
- 모든 매장의 상품을 조회하고 있음
- 해당 매장의 상품만 조회하도록 수정
- dto, service, controller
Closes #351
---
> [itmes]  상품 로직 수정 - 1차 상품, 2차 상품 조회 로직 수 #351

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplication.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/ScheduledSmsSender.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/SmsRepository.java
Backend
예약 발송 api 구현
Closes #349
---
> [messages] 예약-발송-기능-구현 #349

- be15_DevEagles_FE/src/features/users/components/EnrollStoreForm.vue
- be15_DevEagles_FE/src/features/users/views/SignUpView.vue
Frontend
- 매장 가입 전화번호 검증 오류 발생(12자 미만인데도 검증 오류 발생)
- 사업자등록번호 올바른 경우 input 보더가 빨갛게 변해서 오류가 난 것처럼 인식 됌.
1. 회원 가입 진행
2. 매장 정보 입력
Closes #347
---
> [users] 회원 기능 수정 - 회원 가입 매장 정보 검증 오류 #347

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/request/SmsSearchRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/response/SmsDetailResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/response/SmsListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/SmsQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/SmsQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/SmsQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImplTest.java
Backend
보낸 메시지 조회 기능 구현
Closes #361
---
> [messages] 메시지 조회 기능 구현 #361

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaItemSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/SalesQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/request/SalesListFilterRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/PaymentsDTO.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResult.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/mapper/SalesMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/SalesQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImplTest.java
> [sales] 매출 기능 구현 - 매출 조회 기능 구현 #330

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/PrepaidPassSalesCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/SessionPassSalesCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/PrepaidPassSalesCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/SessionPassSalesCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PaymentsRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PrepaidPassSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SessionPassSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaItemSalesRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/SalesQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/request/SalesListFilterRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/PaymentsDTO.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResult.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/mapper/SalesMapper.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/SalesQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImpl.java
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImplTest.java
Backend
- 회원권 매출 수정 기능 구현
Closes #354
---
> [sales] 매출 기능 구현 - 회원권 매출 수정 기능 구현 #354

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageTemplateController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/MessageTemplateCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/MessageTemplateUpdateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/MessageTemplateResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageTemplateService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageTemplateServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplate.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplateType.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/MessageTemplateRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/MessageTemplateQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageTemplateQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/MessageTemplateQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageTemplateServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImplTest.java
Backend
- 메시지 템플릿 등록
- 메시지 템플릿 수정
- 메시지 템플릿 조회
- 메시지 템플릿 삭제
Closes #365
---
> [messages] 템플릿 관련 기능 구현 #365

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/ItemSalesRepository.java
Backend
- repository
Closes #369
---
- 매출 도메인 설정
> [sales] 매출 기능 구현 - 도메인 설정 #369

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessList.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/repository/AccessAuthRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/repository/AccessListRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/StaffCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/CreateStaffRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/response/StaffInfoResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/staffs/api/staffs.js
- be15_DevEagles_FE/src/features/staffs/views/StaffRegistView.vue
Full Stack
- Backend 
- 직원 등록 API 구현
- Frontend
- 직원 등록 API 연동  
Closes #367
---
> [staffs] 직원 기능 구현 - 직원 등록 #367

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/StaffCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/repository/UserRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/controller/StaffQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/request/GetStaffsListRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/response/StaffsListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffRepositoryImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/staffs/api/staffs.js
- be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
Full Stack
- Backend 
- 목록 조회 API 구현
- Frontend
- 목록 조회 API 연동 
- 이름 검색
- 재직 여부 조회    
Closes #377
---
> [staffs] 직원 기능 구현 - 직원 목록 조회 #377

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/controller/PrepaidPassCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/controller/SessionPassCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/dto/request/CustomerPrepaidPassRegistRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/dto/request/CustomerSessionPassRegistRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/CustomerPrepaidPassCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/CustomerSessionPassCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerPrepaidPassCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerSessionPassCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerPrepaidPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerSessionPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/infrastructure/repository/JpaCustomerPrepaidPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/infrastructure/repository/JpaCustomerSessionPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/PrepaidPassQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/SessionPassQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PrepaidPassSalesRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/SessionPassSalesRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerPrepaidPassCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerSessionPassCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Backend
- 고객 회원권 등록 기능 구현
Closes #383
---
> [membership] 회원권 기능 구현 - 고객 회원권 등록 기능 구현 #383

- be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
- be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
- be15_DevEagles_FE/src/features/staffs/views/StaffRegistView.vue
Frontend
- 직원 정보 등록 시 직급에 대한 validation check가 되지 않음 
1. 직원 정보 등록 페이지로 이동
2. 입력 값 없이 직원 정보 등록 버튼 클릭 시 직급 입력 Input에 에러 표시가 되지 않음 
⚠️ **1/4 완료** (미완료 항목 있음)
Closes #384
---
- 직원 등록 시 validation 수정
- 직원 상세 페이지 warning 수정
- 직원 목록 페이지 warning 수정
> [staffs] 직원 기능 수정 - 직원 관리 페이지 수정 #384

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/AutomaticMessageTriggerController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/AutomaticCreateRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/AutomaticMessageTriggerService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageVariableProcessor.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/AutomaticMessageTriggerServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/AutomaticEventType.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplate.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/MessageTemplateRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageTemplateQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
Backend
고객 신규 등록 자동 발송 기능 구현
Closes #393
---
> [messages] 고객 신규 등록 자동 발송 기능 구현 #393

- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
Backend
- 리팩토링 대상: MessageCommandServiceImplTest
- 문제점: 테스트 코드 실행 안됨
- 개선 방향: 테스트 코드 수정
- 수정될 파일들 : MessageCommandServiceImplTest 코드 수정
Closes #401
---
> [messages] 테스트 코드 수정 #401

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/LeaveCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/PlanCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationSettingCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateLeaveRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreatePlanRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateRegularLeaveRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateRegularPlanRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateReservationFullRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/LeaveCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/LeaveQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/PlanQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/request/LeaveListRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/LeaveQueryService.java
- be15_DevEagles_BE/src/main/resources/mappers/features/schedules/LeaveQueryMapper.xml
- be15_DevEagles_BE/src/main/resources/mappers/features/schedules/PlanQueryMapper.xml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/LeaveCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/LeaveQueryServiceTest.java
Backend
기능 몇 개가 param에서 shopid를 받아오는 경우가 있음
1. 일정, 휴무 기능 코드에서
2. param으로 
3. shopid를 받아옴 
⚠️ **1/4 완료** (미완료 항목 있음)
Closes #407
---
> [schedules] CustomUser 사용 #407

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Customer.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerPrepaidPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerSessionPassRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/ItemSalesCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/ItemSalesRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PaymentsInfo.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/ItemSalesCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/ItemSalesRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Backend
- 상품 매출 등록 기능 구현
Closes #373
---
- 상품 매출 등록 기능 구현
> [sales] 매출 기능 구현 - 상품 매출 등록 기능 구현 #373

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/repository/CustomerJpaRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/CustomerElasticsearchController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/dto/response/ReindexStatus.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
Backend
엘라스틱 서치 기능 추가 
- 매장별 고객 데이터 재인덱싱 기능
- 전체 고객 데이터 재인덱싱 기능
Closes #426
---
> [customer] 엘라스틱 서치 기능 추가 - 재인덱싱 코드 구현 #426

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepositoryImpl.java
- be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Full Stack
- Backend
- 직원별 결산(월별 / 기간별) 조회 API 구현 
- Frontend 
-  직원별 결산 조회 API 연동
Closes #409
---
- 매출 내역 조회 시 환불 여부 포함
- 프론트 데이터 매핑 수정
> [staffsales] 직원 결산 기능 구현 - 직원별 결산 조회 #409

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/PutShopRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/IndustryRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/users/views/StoreSettingView.vue
Backend
- 매장 기본 설정에서 매장 설명 폼 생성 요청
.
Closes #421
---
> [shops] 매장 기능 수정 - 매장 설정 설명 폼 누락 #421

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/StaffSalesQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffDetailSalesListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffPaymentsDetailSalesResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffPrimarySalesResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffSalesDetailListResult.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffSecondarySalesResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/StaffSalesQueryService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/StaffSalesQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/support/SalesCalculator.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/StaffSalesQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/staffsales/api/staffsales.js
- be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Full Stack
- Backend
- 직원별 상세 결산(월별 / 기간별) 조회 API 구현 
- Frontend 
-  직원별 상세 결산 조회 API 연동
Closes #410
---
> [staffsales] 직원 결산 기능 구현 -  직원 상세결산 조회 #410

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/controller/ShopCommandController.java
- be15_DevEagles_FE/src/features/profilelink/api/shop.js
- be15_DevEagles_FE/src/features/profilelink/views/ProfileLinkView.vue
- be15_DevEagles_FE/src/features/profilelink/views/PublicProfileView.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
- 프로필 링크를 생성하는 페이지를 구현한다.
Closes #415
---
-프로필 링크 페이지 및 공개 프로필 링크 페이지 구현
> [profilelink] 프로필 링크 생성 페이지 구현#415

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/controller/NotificationController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationSseService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/handler/ReservationNotificationHandler.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationSseServiceTest.java
Backend
- 새로운 예약 신청이 들어오면 알림이 발송되는 기능 구현
Closes #332
---
> [notifications] 예약알림 구현#332

- be15_DevEagles_BE/src/main/resources/mappers/features/schedules/ReservationSearchMapper.xml
- be15_DevEagles_FE/src/features/schedules/api/schedules.js
- be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
- be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
- be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
- be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
Full Stack
목록 조회, 상세 조회, 삭제
Closes #440
---
> [schedules] 예약 목록 관련 api 연동 #440

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationSettingCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/UpdateReservationSettingRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingInitializer.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/ReservationSettingQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingCommandServiceTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/schedules/api/schedules.js
- be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Frontend
예약 설정 api 연동
Closes #459
---
shop에 reservationTerm 때문에 코드 추가함
> [schedules] 예약 설정 연동 #459

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/PutShopRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/SnsRepository.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImplTest.java
- be15_DevEagles_FE/src/features/users/views/StoreSettingView.vue
Backend
sns주소 삭제 기능 수정 요청
.
Closes #438
---
> [shops] 매장 기능 수정 - sns 삭제 에러 수정  #438

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
- be15_DevEagles_FE/src/features/users/api/users.js
- be15_DevEagles_FE/src/features/users/views/LoginView.vue
- be15_DevEagles_FE/src/routes/index.js
- be15_DevEagles_FE/src/store/auth.js
Fullstack
- SecurityConfig : SecurityFilterChain 설정 
- front page 라우팅 시 인증 정보 확인
Closes #472
---
- UserCommandController : security 적용
> [auth] 인증인가 기능 구현 - SpringSecurity 적용 #472

- be15_DevEagles_FE/src/features/schedules/api/schedules.js
- be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
- be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
- be15_DevEagles_FE/src/features/schedules/components/SelectSecondaryItemModal.vue
Frontend
상품 모달 연결, 등록 api 연동
Closes #461
---
> [schedules] 스케줄 등록 연동 #461

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatRoomController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatMessageQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatRoomQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageTemplateController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/MessageTemplateQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
> swagger-설정

- be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
> [staffs] 직원 설정 접근권한 영역 숨김

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImpl.java
- be15_DevEagles_FE/src/features/staffs/components/StaffForm.vue
- be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
- be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
직원 재직 여부 변경 오류 수정
- 조회 시 leftDate 누락
- 설정 시 타입 Check 오류
> [staffs] 직원 기능 수정 - 직원 퇴사 버그 수정

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/request/SalesListFilterRequest.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/ItemSalesDetailResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/PrepaidPassSalesDetailResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SessionPassSalesDetailResponse.java
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/ItemSalesQueryMapper.xml
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/PrepaidPassSalesQueryMapper.xml
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
- be15_DevEagles_BE/src/main/resources/mappers/features/sales/SessionPassSalesQueryMapper.xml
- be15_DevEagles_FE/package.json
- be15_DevEagles_FE/src/features/membership/components/MembershipDetailModal.vue
- be15_DevEagles_FE/src/features/sales/api/sales.js
- be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesEditModal.vue
- be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
- be15_DevEagles_FE/src/features/sales/components/SalesForm.vue
- be15_DevEagles_FE/src/features/sales/components/SalesTableForm.vue
- be15_DevEagles_FE/src/features/sales/styles/SalesDetailModal.css
Full Stack
- UI 개선 및 API 연동
Closes #496
---
- 매출 API 연동
> [sales] 매출 기능 구현 - 매출 수정 및 환불 API 연동 #496

- be15_DevEagles_FE/src/features/notifications/api/notifications.js
- be15_DevEagles_FE/src/features/notifications/components/NotificationList.vue
- be15_DevEagles_FE/src/features/notifications/composables/useNotifications.js
Full Stack
- 공지사항이 발생했을 때 알림 기능 구현
Closes #458
---
-불필요한 주석 삭제
> [notifications] 공지사항 알림 - 불필요한 주석 삭제#458

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageClickRedirectController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageClickService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageClickServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/Sms.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageClickLinkLogRepository.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageClickLinkRepository.java
- be15_DevEagles_BE/src/main/resources/application.yml
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageClickServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
- be15_DevEagles_FE/src/features/messages/api/message.js
- be15_DevEagles_FE/src/features/messages/components/MessageItem.vue
- be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
- be15_DevEagles_FE/src/features/messages/components/modal/ReservationSendModal.vue
- be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
Backend
프로필 링크 로그 클릭 관련 api
Closes #520
---
> [messages] 프로필-링크-로그-클릭-관련-api #520

- be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
Frontend
캘린더 일일 조회 시 예약 가능 시간만 보이게 수정
주 조회 삭제
1. 캘린더 조회 페이지 이동
2. 일일 조회 클릭
3. 시간 오전 12시 확인
Closes #537
---
> [schedules] 캘린더 스타일 변경 #537

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatRoomController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/ChatRoom.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/WebSocketAuthInterceptor.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/dto/response/ChatRoomSummaryResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/AutomaticMessageTriggerController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageVariableProcessor.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/ScheduledSmsSender.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/AutomaticMessageTriggerServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/SmsQueryRepositoryImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/CalendarScheduleQueryService.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImplTest.java
- be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationServiceTest.java
- be15_DevEagles_FE/src/features/chat/composables/socket.js
Backend
예약 등록 시 문자 자동 발송
Closes #535
---
> [messages] 예약-등록-시-문자-자동-발송 #535

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/controller/WorkflowCommandController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/dto/request/ToggleWorkflowCommand.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowCommandService.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/Workflow.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/infrastructure/service/WorkflowCommandServiceImpl.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowQueryResponse.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/controller/WorkflowQueryController.java
- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImpl.java
- be15_DevEagles_FE/src/components/common/BaseTagSelector.vue
- be15_DevEagles_FE/src/features/campaigns/components/CampaignForm.vue
- be15_DevEagles_FE/src/features/coupons/components/CompactCouponSelector.vue
- be15_DevEagles_FE/src/features/coupons/components/CouponSelectorModal.vue
- be15_DevEagles_FE/src/features/workflows/api/workflows.js
- be15_DevEagles_FE/src/features/workflows/components/WorkflowConfigSidebar.vue
- be15_DevEagles_FE/src/features/workflows/components/WorkflowFormBase.vue
- be15_DevEagles_FE/src/features/workflows/composables/useWorkflowForm.js
- be15_DevEagles_FE/src/features/workflows/views/WorkflowCreate.vue
- be15_DevEagles_FE/src/features/workflows/views/WorkflowEdit.vue
- be15_DevEagles_FE/src/features/workflows/views/WorkflowList.vue
Full Stack
워크플로우 자동화 
- API 연동
- 기능 테스트
Closes #345
---
> [workflow] 프론트 백엔드 연동 - 워크플로우 자동화#345

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/SegmentCustomerQueryController.java
- be15_DevEagles_FE/src/components/icons/GiftIcon.vue
- be15_DevEagles_FE/src/components/icons/PlusCircleIcon.vue
- be15_DevEagles_FE/src/components/icons/ReceiptIcon.vue
- be15_DevEagles_FE/src/components/icons/StarIcon.vue
- be15_DevEagles_FE/src/components/layout/TheHeader.vue
- be15_DevEagles_FE/src/features/customer/components/CustomerDetailModal.vue
- be15_DevEagles_FE/src/features/customer/components/CustomerFilterModal.vue
- be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
- be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
- be15_DevEagles_FE/src/features/sales/components/MembershipSalesRegistModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
- be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
- be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
Backend
예약 목록 - 고객 상세 조회에서 상호작용 버튼 이벤트 핸들러 누락 수정
예약 목록에서 고객 상세 조회 -> 버튼 클릭 -> 반응 없음
Closes #542
---
> [customer, reservation] 고객 상세 모달 - 고객 데이터 전달용 이벤트 핸들러 누락 수정 #542

- be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
- be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
- be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
Full Stack
- 조회 버그
조회 하나의 매출에 여러개의 상품 매출이 생기는 버그 및 조회
⚠️ **1/4 완료** (미완료 항목 있음)
Closes #547
---
> [sales] 매출 조회 디버깅#547

- be15_DevEagles_FE/src/components/layout/TheHeader.vue
- be15_DevEagles_FE/src/routes/index.js
Frontend
로그아웃해도 웹소켓 세션이 유지되어 다른 아이디로 로그인해도 그 전 사용자의 세션과 연결됨.
채팅
Closes #551
---
> [chat] 채팅 웹소켓 버그 - 웹소켓 로그아웃시 세션 유지되는 문제 수정#551

- be15_DevEagles_BE/.github/workflows/deploy.yml
- be15_DevEagles_BE/build.gradle
> feat : aws-배포

- be15_DevEagles_FE/src/features/users/views/EmailVerifyPwdView.vue
> fix : 비밀번호 초기화 이메일 인증 실패 시 비밀번호 변경 비활성화
